export const ADD_STAFFS = "ADD_STAFFS"
export const STAFFS_LOADING = "STAFFS_LOADING"
export const STAFFS_FAILED = "STAFFS_FAILED"

export const ADD_DEPARTMENTS = "ADD_DEPARMENTS"
export const DEPARTMENTS_LOADING = "STAFFS_LOADING"
export const DEPARTMENTS_FAILED = "DEPARTMENTS_FAILED"

export const ADD_SALARY = "ADD_SALARY"
export const SALARY_FAILED = "SALARY_FAILED"

export const ADD_NEWSTAFF = "ADD_NEWSTAFF"
export const DELETE_STAFF = "DELETE_STAFF"
export const UPDATE_STAFF = "UPDATE_STAFF"


